date2cal: tx_date2cal_wizard Class Reference
tx_date2cal_wizard Class Reference
Public Member Functions
prepareExtConfig ()
secOptionsOn ()
renderWizard ($params, &$pObj)
Public Attributes
$extConfig = array()
Detailed Description
Calendar Integration Wizard Class
Author:
Stefan Galinski <stefan.galinski@gmail.com>
Definition at line 32 of file class.tx_date2cal_wizard.php.
Member Function Documentation
tx_date2cal_wizard.prepareExtConfig ()
Definition at line 37 of file class.tx_date2cal_wizard.php.
Referenced by renderWizard().
tx_date2cal_wizard.secOptionsOn ()
Activates the secondary options palette
Returns:
void
Definition at line 66 of file class.tx_date2cal_wizard.php.
Referenced by renderWizard().
tx_date2cal_wizard.renderWizard ($ params, &$ pObj)
renders date/datetime fields
Parameters:
array $params TCA informations about date/datetime field
object $pObj TCE forms object (not needed)
Returns:
empty string
Definition at line 77 of file class.tx_date2cal_wizard.php.
References JSCalendar.getInstance(), prepareExtConfig(), and secOptionsOn().
Member Data Documentation
tx_date2cal_wizard.$extConfig = array()
array contains extension configuration
Definition at line 35 of file class.tx_date2cal_wizard.php.
The documentation for this class was generated from the following file:
src/class.tx_date2cal_wizard.php