date2cal: tx_date2cal_befunc Class Reference
tx_date2cal_befunc Class Reference
Public Member Functions
getFlexFormDS_postProcessDS (&$dataStructArray, $conf, $row, $table, $fieldName)
flexformNoTabs (&$dataStructArray)
flexformTabbed (&$dataStructArray)
Detailed Description
Contains a hook for flexform manipulation (adding of calendar wizard)
Author:
Stefan Galinski <stefan.galinski@gmail.com>
Definition at line 32 of file class.tx_date2cal_befunc.php.
Member Function Documentation
tx_date2cal_befunc.getFlexFormDS_postProcessDS (&$ dataStructArray, $ conf, $ row, $ table, $ fieldName)
Hook for manipulating flexform fields Its needed to add the calendar wizard.
Parameters:
array $dataStructArray flexform value (array of xml file)
array $conf configuration of flexform fields (not needed)
array $row flexform informations of special file (not needed)
string $table table (not needed)
string $fieldName field (not needed)
Returns:
void
Definition at line 45 of file class.tx_date2cal_befunc.php.
References flexformNoTabs(), and flexformTabbed().
tx_date2cal_befunc.flexformNoTabs (&$ dataStructArray)
Manipulates flexforms without tabs...
Parameters:
array $dataStructArray flexform value (array of xml file)
Returns:
void
Definition at line 58 of file class.tx_date2cal_befunc.php.
References tx_date2cal_shared.addWizard(), and tx_date2cal_shared.isDateOrDateTime().
Referenced by getFlexFormDS_postProcessDS().
tx_date2cal_befunc.flexformTabbed (&$ dataStructArray)
Manipulates flexforms with tabs...
Parameters:
array $dataStructArray flexform value (array of xml file)
Returns:
void
Definition at line 76 of file class.tx_date2cal_befunc.php.
References tx_date2cal_shared.addWizard(), and tx_date2cal_shared.isDateOrDateTime().
Referenced by getFlexFormDS_postProcessDS().
The documentation for this class was generated from the following file:
src/class.tx_date2cal_befunc.php