date2cal: tx_date2cal_extTables Class Reference
tx_date2cal_extTables Class Reference
Public Member Functions
tx_date2cal_extTables ()
tx_date2cal_writeCacheFile ()
tx_date2cal_setWizard ()
tx_date2cal_toDatetime ()
Public Attributes
$extConf = array()
$cache = ''
$tcaTables = array()
Detailed Description
Initialization class for tx_date2cal
Author:
Stefan Galinski <stefan.galinski@gmail.com>
Definition at line 38 of file ext_tables.php.
Member Function Documentation
tx_date2cal_extTables.tx_date2cal_extTables ()
Constructor :: initializes tx_date2cal :: loads the extension configuration
Returns:
void
Definition at line 56 of file ext_tables.php.
References tx_date2cal_setWizard(), tx_date2cal_toDatetime(), and tx_date2cal_writeCacheFile().
tx_date2cal_extTables.tx_date2cal_writeCacheFile ()
Writes the cache file
Returns:
void
Definition at line 79 of file ext_tables.php.
Referenced by tx_date2cal_extTables().
tx_date2cal_extTables.tx_date2cal_setWizard ()
Sets date2cal wizard to each date/datetime field
Returns:
array tca tables
Definition at line 94 of file ext_tables.php.
References tx_date2cal_shared.addWizard(), and tx_date2cal_shared.isDateOrDateTime().
Referenced by tx_date2cal_extTables().
tx_date2cal_extTables.tx_date2cal_toDatetime ()
Forces start and end fields to add a time selector (just overrides default values) Note: this is only done for tt_content and pages table
Returns:
void
Definition at line 137 of file ext_tables.php.
Referenced by tx_date2cal_extTables().
Member Data Documentation
tx_date2cal_extTables.$extConf = array()
array holds configuration
Definition at line 41 of file ext_tables.php.
tx_date2cal_extTables.$cache = ''
string content of cache file
Definition at line 44 of file ext_tables.php.
tx_date2cal_extTables.$tcaTables = array()
array used tca tables (needed as cache information)
Definition at line 47 of file ext_tables.php.
The documentation for this class was generated from the following file:
ext_tables.php