date2cal: tx_date2cal_shared Class Reference
tx_date2cal_shared Class Reference
Public Member Functions
isDateOrDateTime ($field)
addWizard (&$arrStruct, $type)
Detailed Description
Contains commonly used functions...
Author:
Stefan Galinski <stefan.galinski@gmail.com>
Definition at line 30 of file class.tx_date2cal_shared.php.
Member Function Documentation
tx_date2cal_shared.isDateOrDateTime ($ field)
Checks the given field if its a date or datetime field...
Parameters:
array $field TCEforms field (only the part with type and eval as keys)
Returns:
mixed "date", "datetime" or boolean false if its not a date or datetime field
Definition at line 37 of file class.tx_date2cal_shared.php.
Referenced by tx_date2cal_befunc.flexformNoTabs(), tx_date2cal_befunc.flexformTabbed(), and tx_date2cal_extTables.tx_date2cal_setWizard().
tx_date2cal_shared.addWizard (&$ arrStruct, $ type)
Adds the wizard to a TCEforms field...
Parameters:
array $arrStruct config part of the field
string $type eval type
Returns:
void
Definition at line 59 of file class.tx_date2cal_shared.php.
Referenced by tx_date2cal_befunc.flexformNoTabs(), tx_date2cal_befunc.flexformTabbed(), and tx_date2cal_extTables.tx_date2cal_setWizard().
The documentation for this class was generated from the following file:
src/class.tx_date2cal_shared.php